image: moonpig/build-aws:v0.1.34

stages:
    - deploy-dev-regional
    - deploy-dev-global
    - deploy-test-regional
    - deploy-test-global
    - deploy-dynamic-regional
    - deploy-dynamic-global

deploy-dev-eu-west-1:
  stage: deploy-dev-regional
  script: 
    - echo ${CI_PIPELINE_IID}
    - chmod -R 755 deploy/bash/
    - deploy/bash/deploy-resources ${aws_account_id} ${aws_role_name} eu-west-1 deploy/config/eu-west-1/db dev1 dev

deploy-dev-us-east-1:
  stage: deploy-dev-regional
  script: 
    - chmod -R 755 deploy/bash/
    - deploy/bash/deploy-resources ${aws_account_id} ${aws_role_name} us-east-1 deploy/config/us-east-1/db dev1 dev

deploy-dev-ap-southeast-2:
  stage: deploy-dev-regional
  script: 
    - chmod -R 755 deploy/bash/
    - deploy/bash/deploy-resources ${aws_account_id} ${aws_role_name} ap-southeast-2 deploy/config/ap-southeast-2/db dev1 dev

deploy-dev-global:
  stage: deploy-dev-global
  script: 
    - chmod -R 755 deploy/bash/
    - deploy/bash/deploy-resources ${aws_account_id} ${aws_role_name} eu-west-1 deploy/config/global/db dev1 dev

deploy-test-eu-west-1:
  stage: deploy-test-regional
  script: 
    - echo ${CI_PIPELINE_IID}
    - chmod -R 755 deploy/bash/
    - deploy/bash/deploy-resources ${aws_account_id} ${aws_role_name} eu-west-1 deploy/config/eu-west-1/db QA test

deploy-test-us-east-1:
  stage: deploy-test-regional
  script: 
    - chmod -R 755 deploy/bash/
    - deploy/bash/deploy-resources ${aws_account_id} ${aws_role_name} us-east-1 deploy/config/us-east-1/db QA test

deploy-test-ap-southeast-2:
  stage: deploy-test-regional
  script: 
    - chmod -R 755 deploy/bash/
    - deploy/bash/deploy-resources ${aws_account_id} ${aws_role_name} ap-southeast-2 deploy/config/ap-southeast-2/db QA test

deploy-test-global:
  stage: deploy-test-global
  script: 
    - chmod -R 755 deploy/bash/
    - deploy/bash/deploy-resources ${aws_account_id} ${aws_role_name} eu-west-1 deploy/config/global/db QA test

deploy-dynamic-eu-west-1:
  stage: deploy-dynamic-regional
  variables:
    aws_account_id: ${aws_account_id}
    environment: dynamic
    environment_type: dev
  script: 
    - echo ${CI_PIPELINE_IID}
    - chmod -R 755 deploy/bash/
    - deploy/bash/deploy-resources ${aws_account_id} ${aws_role_name} eu-west-1 deploy/config/eu-west-1/db ${environment} ${environment_type}
  only:
    - triggers

deploy-dynamic-us-east-1:
  stage: deploy-dynamic-regional
  variables:
    aws_account_id: ${aws_account_id}
    environment: dynamic
    environment_type: dev
  script: 
    - chmod -R 755 deploy/bash/
    - deploy/bash/deploy-resources ${aws_account_id} ${aws_role_name} us-east-1 deploy/config/us-east-1/db ${environment} ${environment_type}
  only:
    - triggers

deploy-dynamic-ap-southeast-2:
  stage: deploy-dynamic-regional
  variables:
    aws_account_id: ${aws_account_id}
    environment: dynamic
    environment_type: dev
  script: 
    - chmod -R 755 deploy/bash/
    - deploy/bash/deploy-resources ${aws_account_id} ${aws_role_name} ap-southeast-2 deploy/config/ap-southeast-2/db ${environment} ${environment_type}
  only:
    - triggers

deploy-dynamic-global:
  stage: deploy-dynamic-global
  variables:
    aws_account_id: ${aws_account_id}
    environment: dynamic
    environment_type: dev
  script: 
    - chmod -R 755 deploy/bash/
    - deploy/bash/deploy-resources ${aws_account_id} ${aws_role_name} eu-west-1 deploy/config/global/db ${environment} ${environment_type}
  only:
    - triggers
