image: moonpig/build-aws:v0.1.34

stages:
    - deploy-dev

deploy-eu-west-1:
  stage: deploy-dev
  script: 
    - chmod -R 755 deploy/bash/
    - deploy/bash/deploy-resources ${aws_account_id} ${aws_role_name} eu-west-1 deploy/config/dev/eu-west-1/db