#!/bin/bash

aws_account_id=$1
aws_role_name=$2
aws_region=$3
terragrunt_path=$4
environment=$5
environment_type=$6

. deploy/bash/assume-role $aws_account_id $aws_role_name
deploy/bash/run-terragrunt $terragrunt_path $aws_region $aws_account_id $environment $environment_type