version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip
      - run:
          name: Install awscli
          command: pip install awscli
      - run:
          name: Print the Current Time
          command: date