version: 2

jobs:

  build:

    docker:
       - image: moonpig/build-aws:latest

    # Requires the following environment variables setting:
    # - AWS_ACCESS_KEY_ID
    # - AWS_SECRET_ACCESS_KEY
    # - AWS_DEFAULT_REGION
    steps:
      - run:
          name: AWS
          command: aws sts get-caller-identity
      - run:
          name: Terraform
          command: |
            terraform version
            terragrunt
      - run:
          name: Print the Current Time
          command: date
