version: 2
jobs:
  build:
    docker:
      - image: circleci/terraform:0.11.10
    steps:
      - checkout
      - run:
          name: Update
          command: apt-get update
      - run:
          name: Install pip
          command: apt-get install python-pip
      - run:
          name: Install awscli
          command: pip install awscli
      - run:
          name: Print the Current Time
          command: date