version: 2
jobs:
  build:
    docker:
      - image: circleci/terraform:0.11.10
    steps:
      - checkout
      - run:
          name: AWS
          command: ~/bin/aws sts get-caller-identity
      - run:
          name: Terraform
          command: terraform version
      - run:
          name: Print the Current Time
          command: date
