version: 2
jobs:
  build:
    # Requires the following environment variables setting:
    # - AWS_ACCESS_KEY_ID
    # - AWS_SECRET_ACCESS_KEY
    environment:
      AWS_DEFAULT_REGION: "us-east-1" # Defined locally for now, may need to parameterise
      AWS_ACCOUNT_ID: "452630188168" # Defined locally for now, may need to parameterise
      AWS_ROLE_NAME: "mnpg-content-data-pipeline-dev" # Defined locally for now, may need to parameterise
      TARGET_ENVIRONMENT: "dev" # Defined locally for now, may need to parameterise
    docker:
       - image: moonpig/build-aws:latest
    steps:
      - run:
          name: AWS - Assume Role
          command: |
            echo "Current identity..."
            aws sts get-caller-identity
            echo "Assuming role..."
            ASSUME_ROLE_OUTPUT=$(aws sts assume-role --role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/${AWS_ROLE_NAME} --role-session-name ${AWS_ROLE_NAME}-$(date +%FT%H.%M.%S))
            export AWS_ACCESS_KEY_ID=$(echo ${ASSUME_ROLE_OUTPUT} | jq --raw-output '.Credentials.AccessKeyId')
            export AWS_SECRET_ACCESS_KEY=$(echo ${ASSUME_ROLE_OUTPUT} | jq --raw-output '.Credentials.SecretAccessKey')
            export AWS_SESSION_TOKEN=$(echo ${ASSUME_ROLE_OUTPUT} | jq --raw-output '.Credentials.SessionToken')
            echo "Assumed identity..."
            aws sts get-caller-identity
      - run:
          name: Terraform
          command: |
            ls
            cd ./deploy/config/${TARGET_ENVIRONMENT}/db
            terragrunt plan
            #terraform version
            #terragrunt
