version: 2

jobs:

  build:

    docker:
       - image: ubuntu:latest
    #  - image: circleci/terraform:0.11.10

    # Requires the following environment variables setting:
    # - AWS_ACCESS_KEY_ID
    # - AWS_SECRET_ACCESS_KEY
    # - AWS_DEFAULT_REGION
    steps:
      # - checkout
      # - run:
      #     name: Terraform
      #     command: terraform version
      - run: |
          apt-get update
          apt-get install -y sudo
          sudo apt-get install python3
          curl -O https://bootstrap.pypa.io/get-pip.py
          python get-pip.py --user
          pip install --upgrade pip
          pip install awscli
      # - run:
      #     name: AWS
      #     command: aws sts get-caller-identity
      - run:
          name: Print the Current Time
          command: date
