version: 2
jobs:
  build:
    docker:
      - image: circleci/terraform:0.11.10
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: apt update && apt install awscli, python-pip
      - run:
          name: Print the Current Time
          command: date