version: 2
jobs:
  build:
    # Requires the following environment variables setting:
    # - AWS_ACCESS_KEY_ID
    # - AWS_SECRET_ACCESS_KEY
    environment:
      AWS_DEFAULT_REGION: us-east-1 # Defined locally for now, may need to parameterise
      AWS_ACCOUNT_ID: 452630188168 # Defined locally for now, may need to parameterise
      AWS_ROLE_NAME: mnpg-content-data-pipeline-dev # Defined locally for now, may need to parameterise
    docker:
       - image: moonpig/build-aws:latest
    steps:
      - run:
          name: AWS - Assume Role
          command: |
            aws sts get-caller-identity
            # aws sts assume-role --role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/${AWS_ROLE_NAME} --role-session-name ${AWS_ROLE_NAME}
            # aws sts assume-role --role-arn arn:aws:iam::452630188168:role/mnpg-content-data-pipeline-dev --role-session-name TestSession
            echo ${AWS_ACCOUNT_ID}
            aws sts assume-role --role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/mnpg-content-data-pipeline-dev --role-session-name TestSession
      - run:
          name: Terraform
          command: |
            terraform version
            terragrunt
