version: 2.1

description: moonpig-content-data deployment

orbs:
  deploy_to_aws_with_terragrunt: moonpig-sandbox/deploy_to_aws_with_terragrunt@1.0.16

workflows:
  deploy-multi-region:
    jobs:
    - deploy_to_aws_with_terragrunt/deploy_component:
        name: us-east-1_deploy
        # Environment variables are not YET expanded in config blocks by CircleCI, only "command" blocks.
        # The Orb depends on the environment varibales being set at the project level.
        # aws_access_key_id: ${AWS_ACCESS_KEY_ID}
        aws_account_id: "452630188168" # Needs to be quoted
        aws_region: us-east-1
        aws_role_name: mnpg-content-data-pipeline-dev
        # Environment variables are not YET expanded in config blocks by CircleCI, only "command" blocks.
        # The Orb depends on the environment varibales being set at the project level.
        # aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
        moonpig_aws_build_container_version: latest
        terragrunt_working_dir: ./deploy/config/dev/us-east-1/db
    - deploy_to_aws_with_terragrunt/deploy_component:
        name: eu-west-1_deploy
        # Environment variables are not YET expanded in config blocks by CircleCI, only "command" blocks.
        # The Orb depends on the environment varibales being set at the project level.
        # aws_access_key_id: ${AWS_ACCESS_KEY_ID}
        aws_account_id: "452630188168" # Needs to be quoted
        aws_region: eu-west-1
        aws_role_name: mnpg-content-data-pipeline-dev
        # Environment variables are not YET expanded in config blocks by CircleCI, only "command" blocks.
        # The Orb depends on the environment varibales being set at the project level.
        # aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
        moonpig_aws_build_container_version: latest
        terragrunt_working_dir: ./deploy/config/dev/eu-west-1/db
    - deploy_to_aws_with_terragrunt/deploy_component:
        name: ap-southeast-2_deploy
        # Environment variables are not YET expanded in config blocks by CircleCI, only "command" blocks.
        # The Orb depends on the environment varibales being set at the project level.
        # aws_access_key_id: ${AWS_ACCESS_KEY_ID}
        aws_account_id: "452630188168" # Needs to be quoted
        aws_region: ap-southeast-2
        aws_role_name: mnpg-content-data-pipeline-dev
        # Environment variables are not YET expanded in config blocks by CircleCI, only "command" blocks.
        # The Orb depends on the environment varibales being set at the project level.
        # aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
        moonpig_aws_build_container_version: latest
        terragrunt_working_dir: ./deploy/config/dev/ap-southeast-2/db
    - deploy_to_aws_with_terragrunt/deploy_component:
        name: global_deploy
        requires:
        - us-east-1_deploy
        - eu-west-1_deploy
        - ap-southeast-2_deploy
        # Environment variables are not YET expanded in config blocks by CircleCI, only "command" blocks.
        # The Orb depends on the environment varibales being set at the project level.
        # aws_access_key_id: ${AWS_ACCESS_KEY_ID}
        aws_account_id: "452630188168" # Needs to be quoted
        aws_region: eu-west-1
        aws_role_name: mnpg-content-data-pipeline-dev
        # Environment variables are not YET expanded in config blocks by CircleCI, only "command" blocks.
        # The Orb depends on the environment varibales being set at the project level.
        # aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
        moonpig_aws_build_container_version: latest
        terragrunt_working_dir: ./deploy/config/dev/global/db
