version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install pip
          command: apt install python3-pip
      - run:
          name: Install awscli
          command: pip install awscli
      - run:
          name: Print the Current Time
          command: date