version: 2

jobs:

  build:

    docker:
       - image: ubuntu:latest
    #  - image: circleci/terraform:0.11.10

    # Requires the following environment variables setting:
    # - AWS_ACCESS_KEY_ID
    # - AWS_SECRET_ACCESS_KEY
    # - AWS_DEFAULT_REGION
    steps:
      # - checkout
      # - run:
      #     name: Terraform
      #     command: terraform version
      - run: 
          name: Install
          command: |
            apt-get update
            apt-get install -y sudo
            sudo apt-get install -y curl
            sudo apt-get install -y python3
            sudo apt install -y python3-distutils
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3 get-pip.py --user
            export PATH=~/.local/bin:$PATH
            pip install --upgrade pip
            pip install awscli
      - run:
          name: AWS
          command: aws sts get-caller-identity
      - run:
          name: Print the Current Time
          command: date
