variable TagNameValue {}
variable TagEnvironmentValue {}
variable TagOwnerValue {}
variable TagTeamValue {}
variable TagWorkstreamValue {}
variable ContentStackUpdatesTableName {}
variable ContentStackUpdatesTableReadCapacityUnitsMin {}
variable ContentStackUpdatesTableReadCapacityUnitsMax {}
variable ContentStackUpdatesTableWriteCapacityUnitsMin {}
variable ContentStackUpdatesTableWriteCapacityUnitsMax {}
variable ContentStackUpdatesTableAutoScalePolicyTargetValue {}
