variable ContentStackUpdatesTableName {}
variable ContentStackUpdatesTableReadCapacityUnitsMin {}
variable ContentStackUpdatesTableReadCapacityUnitsMax {}
variable ContentStackUpdatesTableWriteCapacityUnitsMin {}
variable ContentStackUpdatesTableWriteCapacityUnitsMax {}
variable ContentStackUpdatesTableAutoScalePolicyTargetValue {}
