variable TagName {}
variable TagEnvironment {}
variable TagOwner {}
variable TagTeam {}
variable TagWorkstream {}
variable ContentStackUpdatesTableName {}
variable ContentStackUpdatesTableReadCapacityUnitsMin {}
variable ContentStackUpdatesTableReadCapacityUnitsMax {}
variable ContentStackUpdatesTableWriteCapacityUnitsMin {}
variable ContentStackUpdatesTableWriteCapacityUnitsMax {}
variable ContentStackUpdatesTableAutoScalePolicyTargetValue {}
