ContentStackUpdatesTableReadCapacityUnitsMin = 2
ContentStackUpdatesTableReadCapacityUnitsMax = 2
ContentStackUpdatesTableWriteCapacityUnitsMin = 2
ContentStackUpdatesTableWriteCapacityUnitsMax = 2
ContentStackUpdatesTableAutoScalePolicyTargetValue = 50.0